// IDs for projects/activities are now generated by the DB/ORM defaults (CUID)
import { ORPCError } from "@orpc/server";
import { and, asc, eq, inArray, type SQL, sql } from "drizzle-orm";
import { headers } from "next/headers";
import { z } from "zod";
import { memberRoles } from "@/components/features/organizations/types";
import { ProjectParticipantWithUserSchema } from "@/components/features/participants/validation-schemas";
import {
  ProjectActivityFormSchema,
  ProjectActivityWithRelationsSchema,
} from "@/components/features/project-activities/validation-schemas";
import {
  DEFAULT_PROJECT_SORTING_FIELD,
  PROJECT_SORT_FIELDS,
} from "@/components/features/projects/types";
import {
  ProjectFormSchema,
  ProjectWithRelationsSchema,
} from "@/components/features/projects/validation-schemas";
import { auth } from "@/lib/better-auth";
import { db } from "@/lib/drizzle/db";
import {
  projectActivitiesTable,
  projectParticipantsTable,
  projectsTable,
  session as sessionTable,
  user,
} from "@/lib/drizzle/schema";
import { authorized, requireProjectPermissions } from "@/lib/orpc/middleware";

/**
 * Create a new project
 *
 * Requires:
 * - Authentication
 * - Active organization
 * - "create" permission on project resource (owner/admin only)
 */
export const createProject = authorized
  .use(requireProjectPermissions(["create"]))
  .route({
    method: "POST",
    path: "/projects",
    summary: "Create a new project",
    tags: ["project"],
  })
  .input(ProjectFormSchema)
  .output(
    z.object({
      success: z.boolean(),
      project: ProjectWithRelationsSchema,
    }),
  )
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    const newProject = await db
      .insert(projectsTable)
      .values({
        ...input,
        responsibleUserId: context.user.id,
        organizationId: context.session.activeOrganizationId,
      })
      .returning();

    // Fetch the created project with responsible user
    const project = await db.query.projectsTable.findFirst({
      where: eq(projectsTable.id, newProject[0].id),
      with: {
        responsibleUser: true,
        organization: true,
      },
    });

    if (!project) {
      throw new ORPCError("INTERNAL_ERROR", {
        message: "Failed to fetch created project",
      });
    }

    return {
      success: true,
      project,
    };
  });

/**
 * List projects based on user's organization membership
 *
 * Behavior:
 * - Members (role: "member"): See all projects in their organization (read-only)
 * - Admins/Owners: See all projects in their organization (full access)
 *
 * This respects Better Auth's organization-based permissions:
 * - Users can only see projects from organizations they are members of
 * - Projects are isolated by organization
 */
export const listProjects = authorized
  .use(requireProjectPermissions(["read"]))
  .route({
    method: "GET",
    path: "/projects",
    summary: "List all projects in the active organization",
    tags: ["project"],
  })
  .input(
    z
      .object({
        sort_by: z
          .enum(Object.values(PROJECT_SORT_FIELDS))
          .default(DEFAULT_PROJECT_SORTING_FIELD)
          .optional(),
      })
      .optional(),
  )
  .output(z.array(ProjectWithRelationsSchema))
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Determine sort order
    let orderByClause: SQL<unknown>;
    switch (input?.sort_by) {
      case PROJECT_SORT_FIELDS.name:
        orderByClause = asc(sql`lower(${projectsTable.name})`);
        break;
      case PROJECT_SORT_FIELDS.startDate:
        orderByClause = asc(projectsTable.startDate);
        break;
      case PROJECT_SORT_FIELDS.createdAt:
        orderByClause = asc(projectsTable.createdAt);
        break;
      case PROJECT_SORT_FIELDS.updatedAt:
        orderByClause = asc(projectsTable.updatedAt);
        break;
      default:
        orderByClause = asc(projectsTable.createdAt);
    }

    // Get all projects that belong to the user's active organization
    // Permission check ensures user is a member of the organization
    const projects = await db.query.projectsTable.findMany({
      where: eq(
        projectsTable.organizationId,
        context.session.activeOrganizationId,
      ),
      orderBy: [orderByClause],
      with: {
        responsibleUser: true,
        organization: true,
      },
    });

    return projects;
  });

/**
 * Get project details by ID
 *
 * Requires:
 * - Authentication
 * - "read" permission on project resource
 * - Project must belong to user's active organization
 */
export const getProjectById = authorized
  .use(requireProjectPermissions(["read"]))
  .route({
    method: "GET",
    path: "/projects/:id",
    summary: "Get project details by ID",
    tags: ["project"],
  })
  .input(
    z.object({
      id: z.string().describe("Project ID"),
    }),
  )
  .output(ProjectWithRelationsSchema)
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Fetch project and verify it belongs to user's organization
    const project = await db.query.projectsTable.findFirst({
      where: and(
        eq(projectsTable.id, input.id),
        eq(projectsTable.organizationId, context.session.activeOrganizationId),
      ),
      with: {
        responsibleUser: true,
        organization: true,
      },
    });

    if (!project) {
      throw new ORPCError("NOT_FOUND", {
        message: "Project not found or you don't have access to it",
      });
    }

    return project;
  });

/**
 * Update project details
 *
 * Requires:
 * - Authentication
 * - "update" permission on project resource (admin/owner only)
 * - Project must belong to user's active organization
 */
export const updateProject = authorized
  .use(requireProjectPermissions(["update"]))
  .route({
    method: "PATCH",
    path: "/projects/:id",
    summary: "Update project details",
    tags: ["project"],
  })
  .input(
    z.object({
      id: z.string().describe("Project ID"),
      data: ProjectFormSchema.partial(),
    }),
  )
  .output(
    z.object({
      success: z.boolean(),
      project: ProjectWithRelationsSchema,
    }),
  )
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Verify project belongs to user's organization before updating
    const [existingProject] = await db
      .select()
      .from(projectsTable)
      .where(
        and(
          eq(projectsTable.id, input.id),
          eq(projectsTable.organizationId, context.session.activeOrganizationId),
        ),
      )
      .limit(1);

    if (!existingProject) {
      throw new ORPCError("NOT_FOUND", {
        message: "This Project was not found",
      });
    }

    if (existingProject.organizationId !== context.session.activeOrganizationId) {
      throw new ORPCError("FORBIDDEN", {
        message: "You don't have permission to update this project",
      });
    }

    await db
      .update(projectsTable)
      .set(input.data)
      .where(eq(projectsTable.id, input.id));

    // Fetch the updated project with responsible user
    const project = await db.query.projectsTable.findFirst({
      where: eq(projectsTable.id, input.id),
      with: {
        responsibleUser: true,
        organization: true,
      },
    });

    if (!project) {
      throw new ORPCError("INTERNAL_ERROR", {
        message: "Failed to fetch updated project",
      });
    }

    return {
      success: true,
      project,
    };
  });

/**
 * Delete a project
 *
 * Requires:
 * - Authentication
 * - "delete" permission on project resource (owner only)
 * - Project must belong to user's active organization
 */
export const deleteProject = authorized
  .use(requireProjectPermissions(["delete"]))
  .route({
    method: "DELETE",
    path: "/projects/:id",
    summary: "Delete a project",
    tags: ["project"],
  })
  .input(
    z.object({
      id: z.string().describe("Project ID"),
    }),
  )
  .output(
    z.object({
      success: z.boolean(),
    }),
  )
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Verify project exists and belongs to organization
    const [existingProject] = await db
      .select()
      .from(projectsTable)
      .where(
        and(
          eq(projectsTable.id, input.id),
          eq(projectsTable.organizationId, context.session.activeOrganizationId),
        ),
      )
      .limit(1);

    if (!existingProject) {
      throw new ORPCError("NOT_FOUND", {
        message: "Project not found or you don't have access to it",
      });
    }

    // Delete the project
    await db.delete(projectsTable).where(eq(projectsTable.id, input.id));

    return {
      success: true,
    };
  });

/**
 * Set active project for the session
 *
 * Requires:
 * - Authentication
 * - "read" permission on project resource
 * - Project must belong to user's active organization (if projectId is provided)
 */
export const setActiveProject = authorized
  .input(
    z.object({
      projectId: z.string().optional(),
    }),
  )
  .handler(async ({ input, context }) => {
    // If projectId is provided, verify user has access to it
    if (input.projectId) {
      if (!context.session.activeOrganizationId) {
        throw new ORPCError("BAD_REQUEST", {
          message: "No active organization. Please select an organization first.",
        });
      }

      const { role } = await auth.api.getActiveMemberRole({
        headers: await headers(),
      });

      if (role !== memberRoles.Employee && role !== memberRoles.Owner) {
        throw new ORPCError("FORBIDDEN", {
          message: "You don't have permission to set an active project",
        });
      }

      // Verify project belongs to user's organization
      const [existingProject] = await db
        .select()
        .from(projectsTable)
        .where(
          and(
            eq(projectsTable.id, input.projectId),
            eq(
              projectsTable.organizationId,
              context.session.activeOrganizationId,
            ),
          ),
        )
        .limit(1);

      if (!existingProject) {
        throw new ORPCError("NOT_FOUND", {
          message: "This Project was not found",
        });
      }

      if (
        existingProject.organizationId !== context.session.activeOrganizationId
      ) {
        throw new ORPCError("FORBIDDEN", {
          message: "You don't have permission to set this project as active",
        });
      }
    }

    await db
      .update(sessionTable)
      .set({
        activeProjectId: input.projectId,
      })
      .where(eq(sessionTable.id, context.session.id));

    return {
      success: true,
    };
  });

/**
 * Get project participants with details
 *
 * Requires:
 * - Authentication
 * - "read" permission on project resource
 * - Project must belong to user's active organization
 */
export const getProjectParticipants = authorized
  .use(requireProjectPermissions(["read"]))
  .route({
    method: "GET",
    path: "/projects/:id/participants",
    summary: "Get project participants with user details",
    tags: ["project"],
  })
  .input(
    z.object({
      projectId: z.string().describe("Project ID"),
    }),
  )
  .output(z.array(ProjectParticipantWithUserSchema))
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Verify project belongs to user's organization
    const [project] = await db
      .select()
      .from(projectsTable)
      .where(
        and(
          eq(projectsTable.id, input.projectId),
          eq(projectsTable.organizationId, context.session.activeOrganizationId),
        ),
      )
      .limit(1);

    if (!project) {
      throw new ORPCError("FORBIDDEN", {
        message: "You don't have access to this project",
      });
    }

    // Get all participants for this project with user details
    const participants = await db
      .select({
        id: projectParticipantsTable.id,
        projectId: projectParticipantsTable.projectId,
        memberId: projectParticipantsTable.memberId,
        userId: projectParticipantsTable.userId,
        createdAt: projectParticipantsTable.createdAt,
        updatedAt: projectParticipantsTable.updatedAt,
        user: {
          id: user.id,
          name: user.name,
          email: user.email,
          image: user.image,
        },
      })
      .from(projectParticipantsTable)
      .innerJoin(user, eq(projectParticipantsTable.userId, user.id))
      .where(eq(projectParticipantsTable.projectId, input.projectId));

    // NOTE: Demo delay has been moved into a global orpc middleware

    return participants;
  });

/**
 * Batch delete projects
 *
 * Requires:
 * - Authentication
 * - "delete" permission on project resource (owner only)
 * - All projects must belong to user's active organization
 */
export const batchDeleteProjects = authorized
  .use(requireProjectPermissions(["delete"]))
  .route({
    method: "DELETE",
    path: "/projects/batch",
    summary: "Batch delete multiple projects",
    tags: ["project"],
  })
  .input(
    z.object({
      projectIds: z.array(z.string()).min(1),
    }),
  )
  .output(
    z.object({
      success: z.boolean(),
      deletedCount: z.number(),
    }),
  )
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Verify all projects belong to user's organization
    const projectsToDelete = await db
      .select({
        id: projectsTable.id,
      })
      .from(projectsTable)
      .where(
        and(
          inArray(projectsTable.id, input.projectIds),
          eq(projectsTable.organizationId, context.session.activeOrganizationId),
        ),
      );

    if (projectsToDelete.length !== input.projectIds.length) {
      throw new ORPCError("FORBIDDEN", {
        message:
          "Some projects don't exist or you don't have permission to delete them",
      });
    }

    // Delete the projects
    const result = await db
      .delete(projectsTable)
      .where(
        and(
          inArray(projectsTable.id, input.projectIds),
          eq(projectsTable.organizationId, context.session.activeOrganizationId),
        ),
      );

    return {
      success: true,
      deletedCount: result.rowCount || 0,
    };
  });

// ============================================================================
// PROJECT ACTIVITY PROCEDURES
// ============================================================================

/**
 * Helper to verify project belongs to user's organization
 */
async function verifyProjectAccess(
  projectId: string,
  organizationId: string,
): Promise<boolean> {
  const [project] = await db
    .select()
    .from(projectsTable)
    .where(
      and(
        eq(projectsTable.id, projectId),
        eq(projectsTable.organizationId, organizationId),
      ),
    )
    .limit(1);

  return !!project;
}

/**
 * Get project activities
 *
 * Requires:
 * - Authentication
 * - "read" permission on project resource
 * - Project must belong to user's active organization
 */
export const getProjectActivities = authorized
  .use(requireProjectPermissions(["read"]))
  .route({
    method: "GET",
    path: "/projects/:id/activities",
    summary: "Get project activities",
    tags: ["project", "activity"],
  })
  .input(
    z.object({
      projectId: z.string().describe("Project ID"),
    }),
  )
  .output(z.array(ProjectActivityWithRelationsSchema))
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Verify project belongs to user's organization
    const hasAccess = await verifyProjectAccess(
      input.projectId,
      context.session.activeOrganizationId,
    );

    if (!hasAccess) {
      throw new ORPCError("FORBIDDEN", {
        message: "You don't have access to this project",
      });
    }

    // Get all activities for this project
    const activities = await db.query.projectActivitiesTable.findMany({
      where: eq(projectActivitiesTable.projectId, input.projectId),
      orderBy: [asc(projectActivitiesTable.createdAt)],
    });

    return activities;
  });

/**
 * Create a new project activity
 *
 * Requires:
 * - Authentication
 * - "update" permission on project resource (owner/admin only)
 *   Creating activities is considered an "edit project" operation
 * - Project must belong to user's active organization
 */
export const createProjectActivity = authorized
  .use(requireProjectPermissions(["update"]))
  .route({
    method: "POST",
    path: "/projects/:id/activities",
    summary: "Create a new project activity",
    tags: ["project", "activity"],
  })
  .input(ProjectActivityFormSchema)
  .output(
    z.object({
      success: z.boolean(),
      activity: ProjectActivityWithRelationsSchema,
    }),
  )
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Verify project belongs to user's organization
    const hasAccess = await verifyProjectAccess(
      input.projectId,
      context.session.activeOrganizationId,
    );

    if (!hasAccess) {
      throw new ORPCError("FORBIDDEN", {
        message: "You don't have access to this project",
      });
    }

    const [newActivity] = await db
      .insert(projectActivitiesTable)
      .values({
        projectId: input.projectId,
        activityType: input.activityType,
        distanceKm: input.distanceKm.toString(),
        description: input.description,
        activityDate: input.activityDate,
      })
      .returning();

    return {
      success: true,
      activity: newActivity,
    };
  });

/**
 * Update a project activity
 *
 * Requires:
 * - Authentication
 * - "update" permission on project resource (owner/admin only)
 *   Updating activities is considered an "edit project" operation
 * - Activity must belong to a project in user's active organization
 */
export const updateProjectActivity = authorized
  .use(requireProjectPermissions(["update"]))
  .route({
    method: "PATCH",
    path: "/projects/:projectId/activities/:id",
    summary: "Update a project activity",
    tags: ["project", "activity"],
  })
  .input(
    z.object({
      id: z.string().describe("Activity ID"),
      data: ProjectActivityFormSchema.omit({ projectId: true }).partial(),
    }),
  )
  .output(
    z.object({
      success: z.boolean(),
      activity: ProjectActivityWithRelationsSchema,
    }),
  )
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Fetch activity and verify it belongs to user's organization via project
    const [existingActivity] = await db
      .select({
        activity: projectActivitiesTable,
        projectOrgId: projectsTable.organizationId,
      })
      .from(projectActivitiesTable)
      .innerJoin(
        projectsTable,
        eq(projectActivitiesTable.projectId, projectsTable.id),
      )
      .where(eq(projectActivitiesTable.id, input.id))
      .limit(1);

    if (!existingActivity) {
      throw new ORPCError("NOT_FOUND", {
        message: "Activity not found",
      });
    }

    if (existingActivity.projectOrgId !== context.session.activeOrganizationId) {
      throw new ORPCError("FORBIDDEN", {
        message: "You don't have permission to update this activity",
      });
    }

    const { distanceKm, ...restData } = input.data;
    const updateData: typeof restData & { distanceKm?: string } = { ...restData };
    if (distanceKm !== undefined) {
      updateData.distanceKm = distanceKm.toString();
    }

    const [updatedActivity] = await db
      .update(projectActivitiesTable)
      .set(updateData)
      .where(eq(projectActivitiesTable.id, input.id))
      .returning();

    return {
      success: true,
      activity: updatedActivity,
    };
  });

/**
 * Delete a project activity
 *
 * Requires:
 * - Authentication
 * - "update" permission on project resource (owner/admin only)
 *   Deleting activities is considered an "edit project" operation
 * - Activity must belong to a project in user's active organization
 */
export const deleteProjectActivity = authorized
  .use(requireProjectPermissions(["update"]))
  .route({
    method: "DELETE",
    path: "/projects/:projectId/activities/:id",
    summary: "Delete a project activity",
    tags: ["project", "activity"],
  })
  .input(
    z.object({
      id: z.string().describe("Activity ID"),
    }),
  )
  .output(
    z.object({
      success: z.boolean(),
    }),
  )
  .handler(async ({ input, context }) => {
    if (!context.session.activeOrganizationId) {
      throw new ORPCError("BAD_REQUEST", {
        message: "No active organization. Please select an organization first.",
      });
    }

    // Fetch activity and verify it belongs to user's organization via project
    const [existingActivity] = await db
      .select({
        activity: projectActivitiesTable,
        projectOrgId: projectsTable.organizationId,
      })
      .from(projectActivitiesTable)
      .innerJoin(
        projectsTable,
        eq(projectActivitiesTable.projectId, projectsTable.id),
      )
      .where(eq(projectActivitiesTable.id, input.id))
      .limit(1);

    if (!existingActivity) {
      throw new ORPCError("NOT_FOUND", {
        message: "Activity not found",
      });
    }

    if (existingActivity.projectOrgId !== context.session.activeOrganizationId) {
      throw new ORPCError("FORBIDDEN", {
        message: "You don't have permission to delete this activity",
      });
    }

    await db
      .delete(projectActivitiesTable)
      .where(eq(projectActivitiesTable.id, input.id));

    return {
      success: true,
    };
  });
